GET http://localhost:8080/api/v1/products
GET http://localhost:8080/api/v1/products/1


POST /api/v1/orders HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "items": [
    {
      "product_id": 1,
      "quantity": 2
    }
  ]
} 

GET http://localhost:8080/api/v1/orders/11


POST http://localhost:8080/api/v1/orders/11/cancel


POST http://localhost:8080/api/v1/orders/11/pay

### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "user4@example.com",
  "password": "password123"
}


//Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "user4@example.com",
  "password": "password123"
}


//create order 
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "items": [
    {
      "product_id": 1,
      "quantity": 1
    }
  ],
}


POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwicm9sZSI6InVzZXIiLCJleHAiOjE3ODcwNTQyNzgsImlhdCI6MTc4Njk2Nzg3OH0.RH6DdidL_yVLS0OqoJGQ3CcRkrc_ZJCoiW7cGJpvz9E

{
  "items": [
    {
      "product_id": 2,
      "quantity": 1
    }
  ]
}


GET http://localhost:8080/api/v1/orders/43
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOCwicm9sZSI6InVzZXIiLCJleHAiOjE3ODcwNTQyNzgsImlhdCI6MTc4Njk2Nzg3OH0.RH6DdidL_yVLS0OqoJGQ3CcRkrc_ZJCoiW7cGJpvz9E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwicm9sZSI6InVzZXIiLCJleHAiOjE3ODcwNTQzMjQsImlhdCI6MTc4Njk2NzkyNH0.dO-zDCkHYhr-t9gwa2fQFZ-iyulitHhTqyrVoAQrBzU


//Register admin
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}

//Login admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}

//от обычного и от адм
GET http://localhost:8080/api/v1/admin/orders
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOSwicm9sZSI6InVzZXIiLCJleHAiOjE3ODcwNTczODYsImlhdCI6MTc4Njk3MDk4Nn0.sNYoGgGhAoJ-owluNbluQzP2A8IzbblCJANYFAdsTDQ
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMCwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzg3MDU3MzA1LCJpYXQiOjE3ODY5NzA5MDV9.irfhZmI2XzO9Hjy2xQy9wQieLcqGzkHJ1SpG0xxoLHs

GET http://localhost:8080/api/v1/admin/orders

PATCH http://localhost:8080/api/v1/admin/orders/42/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMCwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzg3MDU3MzA1LCJpYXQiOjE3ODY5NzA5MDV9.irfhZmI2XzO9Hjy2xQy9wQieLcqGzkHJ1SpG0xxoLHs
Content-Type: application/json

{
  "status": "pending"
}